Support selecting between version in the docs
hoprnet/hopr-docs pull request #5
Opened 2021-11-25 12:27 UTC by KedziaPawel

**Solution overview:**
In order to have information about the releases, I've used the GitHub API.
Unfortunately, Docosaurus doesn't support custom react components in the navbar. That's why I've used the react portal to add versions to the dropdown list.

Flow proposition:
1. Developer creates branch name "release/X.X.X".
2. Developer does local changes and pushes the branch.
3. The pipeline triggers (Github Actions), builds, deploys the documentation to the "https://docs.hoprnet.org/X.X.X" and tags release as X.X.X (deployment and tagging could be also a manual process, it depends on the team needs).
4. User refreshes the docs page, the information about the new release is fetched from GitHub and added to versions list.

Note: 
I have assumpted that master would be deployed to the "https://docs.hoprnet.org/latest".

The biggest advantage of this is solution is that it is automatic. There is no need to make any manual actions, for example, rebuild and redeploy the previous releases so they would have the latest versions in the dropdown.

**Useful links related to PR:**
https://docusaurus.io/docs/api/themes/configuration#navbar-items
https://reactjs.org/docs/portals.html
https://docs.github.com/en/rest/reference/repos#releases

Closes #1

2021-11-29 06:57 UTC, tolbrino requested changes
Thanks! The approach is sound. Could you add the requested documentation?

2021-11-29 06:57 UTC, tolbrino commented on src/api/github/consts.js
> +export const ENDPOINTS = {
Please add a link to the respective API docs.

2021-11-29 06:57 UTC, tolbrino commented on src/portals/DocsVersion.js
> +import React, { useEffect, useState } from "react";
Please document the component so the next person understands its use.

2021-12-05 12:03 UTC, KedziaPawel commented on src/api/github/consts.js
> +export const ENDPOINTS = {
done

2021-12-05 12:03 UTC, KedziaPawel commented on src/portals/DocsVersion.js
> +import React, { useEffect, useState } from "react";
done

2022-01-11 11:19 UTC, QYuQianchen commented
Hey @KedziaPawel Have you "submit work" on Gitcoin?

2022-01-24 14:07 UTC, tolbrino commented
Approach was clear and used as input for the final version. Closing this PR.

2022-01-24 14:07 UTC, closed without merging